
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label7;
	private global::Gtk.Entry s1;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label8;
	private global::Gtk.Entry s2;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Button button6;
	private global::Gtk.Label res;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.hbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label7]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.s1 = new global::Gtk.Entry ();
		this.s1.CanFocus = true;
		this.s1.Name = "s1";
		this.s1.IsEditable = true;
		this.s1.InvisibleChar = '•';
		this.hbox4.Add (this.s1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.s1]));
		w2.Position = 1;
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.hbox3.Add (this.label8);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label8]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.s2 = new global::Gtk.Entry ();
		this.s2.CanFocus = true;
		this.s2.Name = "s2";
		this.s2.IsEditable = true;
		this.s2.InvisibleChar = '•';
		this.hbox3.Add (this.s2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.s2]));
		w5.Position = 1;
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		// Container child button6.Gtk.Container+ContainerChild
		global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w8 = new global::Gtk.HBox ();
		w8.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w9 = new global::Gtk.Image ();
		w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		w8.Add (w9);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w11 = new global::Gtk.Label ();
		w11.LabelProp = global::Mono.Unix.Catalog.GetString ("Sumar");
		w11.UseUnderline = true;
		w8.Add (w11);
		w7.Add (w8);
		this.button6.Add (w7);
		this.hbox5.Add (this.button6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.button6]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.res = new global::Gtk.Label ();
		this.res.Name = "res";
		this.res.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.hbox5.Add (this.res);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.res]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button6.Clicked += new global::System.EventHandler (this.Sumar);
	}
}
